# Labeler configuration for actions/labeler
# Maps file paths to labels

# Scope labels
api:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

shared:
  - changed-files:
      - any-glob-to-any-file: 'packages/shared/**'

# Type labels
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '*.yml'
          - '*.yaml'

testing:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - '**/vitest.config.ts'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'pnpm-lock.yaml'
          - '**/package.json'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile*'
          - 'docker-compose*.yml'
